version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: docker/dev/web/Dockerfile
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./web/:/usr/src/web/
    ports:
      - "8888:8000"
    env_file:
      - docker/dev/env/.dev.env
    depends_on:
      - db
#      - redis
  db:
    image: postgres:13.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - docker/dev/env/.db.env
#  redis:
#    image: redis:6.0-rc3-buster
#    ports:
#      - "6379:6379"

volumes:
  postgres_data:
