# Generated by Django 3.2.11 on 2023-09-08 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeRateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_id', models.CharField(max_length=255)),
                ('currency_name', models.CharField(max_length=255)),
                ('num_code', models.CharField(max_length=255)),
                ('char_code', models.CharField(max_length=255)),
                ('nominal', models.IntegerField()),
                ('exchange_rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('previous_rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
