# Generated by Django 3.2.11 on 2023-09-11 09:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_code', models.CharField(max_length=255)),
                ('currency_name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Котируемая валюта',
                'verbose_name_plural': 'Котируемые валюты',
            },
        ),
        migrations.CreateModel(
            name='ExchangeRateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_id', models.CharField(max_length=255)),
                ('currency_name', models.CharField(max_length=255)),
                ('num_code', models.CharField(max_length=255)),
                ('char_code', models.CharField(max_length=255)),
                ('nominal', models.IntegerField()),
                ('value', models.DecimalField(decimal_places=4, max_digits=10)),
                ('previous_rate', models.DecimalField(decimal_places=4, max_digits=10)),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='TrackedCurrency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('threshold', models.DecimalField(decimal_places=4, max_digits=10)),
                ('currency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracked_currencies', to='main.currency')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracked_currencies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Отслеживаемая КВ',
                'verbose_name_plural': 'Отслеживаемые КВ',
            },
        ),
    ]
